dist: trusty
language: python

python:
  - "3.7"

install:
  - pip install -e .

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-6.0
      - ubuntu-toolchain-r-test
    packages:
      - llvm-6.0
script:
  - pytest
